import scanpy as sc

# Load the unannotated single-cell RNA-seq dataset
adata = sc.read_h5ad('/cs/student/projects2/aisd/2024/shekchu/projects/cell_agents/remove_label/dataset_restricted_with_cluster.h5ad')

# Identify mitochondrial genes (assuming genes starting with MT-)
adata.var['mt'] = adata.var_names.str.startswith('MT-')

# Calculate QC metrics including the percentage of counts from mitochondrial genes
sc.pp.calculate_qc_metrics(adata, qc_vars=['mt'], inplace=True)

# Filter out cells with >20 percent mitochondrial counts and with total counts less than 500
# Replaced the erroneous adata.obs.n_counts with adata.obs.total_counts which is generated by calculate_qc_metrics
adata = adata[adata.obs.pct_counts_mt < 20, :]
adata = adata[adata.obs.total_counts >= 500, :]

# Normalize total counts per cell to 1e4 and log-transform the data
sc.pp.normalize_total(adata, target_sum=1e4)
sc.pp.log1p(adata)

# Save the preprocessed and normalized dataset
adata.write('./output/o3_with_cluster/preprocessed_dataset.h5ad')
